@startuml
class Chain < modules > {
  - self
  - __private: {}
  .. library ..
  - logger
  - db
  - genesisblock
  - bus
  - balancesSequence
  - logic.block
  - logic.transaction
  .. modules ..
  - accounts
  - blocks
  - rounds
  - transactions
  -- Methods --
  + Chain (logger, block, transaction, db,
  genesisblock, bus, balancesSequence)
  + saveGenesisBlock (cb)
  + saveBlock (block, cb)
  + afterSave (block, cb)
  + deleteBlock (blockId, cb)
  + deleteAfterBlock (blockId, cb)
  + applyGenesisBlock (block, cb)
  + applyBlock (block, broadcast, cb, saveBlock)
  + deleteLastBlock (cb)
  + recoverChain (cb)
  + onBind (scope)
  .. __private ..
  - promiseTransactions (t, block, blockPromises)
  - applyTransaction (block, transaction, sender, cb)
  - popLastBlock (oldLastBlock, cb)

}
@enduml
