@startuml
class Process < modules > {
  - self
  - __private: {}
  .. library ..
  - logger
  - logic.peers
  - logic.transaction
  - logic.block
  - schema
  - db
  - dbSequence
  - sequence
  - genesisblock
  .. modules ..
  - accounts
  - blocks
  - delegates
  - loader
  - rounds
  - transactions
  - transport
  -- Methods --
  + Process (logger, block, peers,
  transaction, schema, db,
  dbSequence, sequence, genesisblock)
  + getCommonBlock (peer, height, cb)
  + loadBlocksOffset (limit, offset, verify, cb)
  + loadBlocksFromPeer (peer, cb)
  + generateBlock (keypair, timestamp, cb)
  + onReceiveBlock (block)
  + onBind (scope)
  .. __private ..
  - receiveBlock (block, cb)
}
@enduml
