@startuml
class Utils < modules > {
  - self
  - __private: {}
  .. library ..
  - logger
  - db
  - dbSequence
  - genesisblock
  - logic.block
  - logic.transaction
  .. modules ..
  - blocks
  -- Methods --
  + Utils (logger, block, transaction,
  db, dbSequence, genesisblock)
  + readDbRows (rows)
  + loadBlocksPart (filter, cb)
  + loadLastBlock (cb)
  + getIdSequence (height, cb)
  + loadBlocksData (filter, options, cb)
  + getBlockProgressLogger (transactionsCount,
  logsFrequency, msg)
  + aggregateBlocksReward (filter, cb)
  + onBind (scope)
}
@enduml
