@startuml
class Verify < modules > {
  - self
  - __private: {}
  .. library ..
  - logger
  - db
  - logic.block
  - logic.transaction
  .. modules ..
  - accounts
  - blocks
  - delegates
  - transactions
  -- Methods --
  + Verify (logger, block, transaction, db)
  + verifyBlock (block)
  + processBlock (block, broadcast,
  cb, saveBlock)
  + onBind (scope)
  .. __private ..
  - checkTransaction (block, transaction, cb)
}
@enduml
