@startuml
class BlockReward < logic > {
  - __private: {}
  .. this ..
  + milestones
  + distance
  + rewardOffset
  -- Methods --
  + BlockReward ()
  + calcMilestone (height)
  + calcReward (height)
  + calcSupply (height)
  .. __private ..
  - parseHeight (height)
}
@endtuml
