@startuml
class Broadcaster < logic > {
  - __private: {}
  - self
  .. self ..
  + config
  + consensus
  + queue
  + routes
  .. library ..
  - logger
  - logic.peers
  - logic.transaction
  - config.broadcasts
  - config.forging.force
  .. modules ..
  - peers
  - transport
  - transactions
  -- Methods --
  + Broadcaster (broadcasts, force,
  peers, transaction, logger)
  + bind (peers, transport, transactions)
  + getPeers (params, cb)
  + enqueue (params, options)
  + broadcast (params, options, cb)
  + maxRelays (object)
  .. __private ..
  - filterQueue (cb)
  - filterTransaction (transaction, cb)
  - squashQueue (broadcasts)
  - releaseQueue (cb)
}
@endtuml
