@startuml
class DApp < logic > {
  - __private: {}
  - library
  .. library object ..
  - db
  - logger
  - schema
  - network
  -- Methods --
  + DApp (db, logger, schema, network)
  + create (data, trs)
  + calculateFee (trs, sender)
  + verify (trs, sender, cb)
  + process (trs, sender, cb)
  + getBytes (trs)
  + apply (trs, block, sender, cb)
  + undo (trs, block, sender, cb)
  + applyUnconfirmed (trs, sender, cb)
  + undoUnconfirmed (trs, sender, cb)
  + objectNormalize (trs)
  + dbRead (raw)
  + dbSave (trs)
  + afterSave (trs, cb)
  + ready (trs, sender)
}
@endtuml
