@startuml
class Round < logic > {
  ..this..
  - scope: {}
  - t: t
  .. scope ..
  - backwards
  - round
  - roundOutsiders
  - roundDelegates
  - library.logger
  - modules.accounts
  - block.generatorPublicKey
  - block.id
  - block.height
  -- Methods --
  + Round (scope, t)
  + mergeBlockGenerator ()
  + updateMissedBlocks ()
  + getVotes ()
  + updateVotes ()
  + markBlockId ()
  + flushRound ()
  + truncateBlocks ()
  + applyRound ()
  + land ()
}
@endtuml
