@startuml
class Transaction < logic > {
  - __private: {}
  - self: this
  .. self ..
  - unconfirmed: {transactions:[], index:{}}
  - bundled: {transactions:[], index:{}}
  - queued: {transactions:[], index:{}}
  - multisignature: {transactions:[], index:{}}
  - expiryInterval: 30000
  - bundledInterval: broadcastInterval
  - bundleLimit: releaseLimit
  - processed: 0
  - processBundled: timmer
  - expireTransactions: timmer
  .. library ..
  - logger
  - bus
  - logic.transaction
  - config.broadcasts.broadcastInterval
  - config.broadcasts.releaseLimit
  .. modules ..
  - accounts
  - transactions
  - loader
  -- Methods --
  + TransactionPool (broadcastInterval,
  releaseLimit, transaction, bus, logger)
  + bind (accounts, transactions, loader)
  + transactionInPool (id)
  + getUnconfirmedTransaction (id)
  + getBundledTransaction (id)
  + getQueuedTransaction (id)
  + getMultisignatureTransaction (id)
  + getUnconfirmedTransactionList (reverse, limit)
  + getBundledTransactionList (reverse, limit)
  + getQueuedTransactionList (reverse, limit)
  + getMultisignatureTransactionList (reverse, ready, limit)
  + getMergedTransactionList (reverse, limit)
  + addUnconfirmedTransaction (transaction)
  + removeUnconfirmedTransaction (id)
  + countUnconfirmed ()
  + addBundledTransaction (transaction)
  + removeBundledTransaction (id)
  + countBundled ()
  + addQueuedTransaction (transaction)
  + removeQueuedTransaction (id)
  + countQueued ()
  + addMultisignatureTransaction (transaction)
  + removeMultisignatureTransaction (id)
  + countMultisignature ()
  + receiveTransactions (transactions, broadcast, cb)
  + reindexQueues ()
  + processBundled (cb)
  + processUnconfirmedTransaction (transaction, broadcast, cb)
  + queueTransaction (transaction, cb)
  + applyUnconfirmedList (cb)
  + applyUnconfirmedIds (ids, cb)
  + undoUnconfirmedList (cb)
  + expireTransactions (cb)
  + fillPool (cb)
  .. __private ..
  - getTransactionList (transactions, reverse, limit)
  - processVerifyTransaction (transaction, broadcast, cb)
  - applyUnconfirmedList (transactions, cb)
  - transactionTimeOut (transaction)
  - expireTransactions (transactions, parentIds, cb)
}
@endtuml
