@startuml
class DApps < modules > {
  - __private: {}
  - self: this
  - internal: {}
  + shared: {}
  .. __private ..
  - assetTypes[5]: new DApp(db, logger, schema, network)
  - assetTypes[6]: new InTransfer(db, schema)
  - assetTypes[7]: new OutTransfer(db, schema, logger)
  .. library ..
  - logger
  - db
  - public
  - network
  - schema
  - ed
  - balancesSequence
  - logic.transaction
  - config.dapp
  .. modules ..
  - transactions
  - accounts
  - peers
  - sql
  -- Methods --
  + DApps(cb, scope)
  + sandboxApi(call, args, cb)
  + message(dappid, body, cb)
  + request(dappid, method, path, query, cb)
  + onBind (scope)
  + onBlockchainReady()
  + onDeleteBlocksBefore(block)
  + onNewBlock(block, broadcast)
  + isLoaded()
  .. __private ..
  - get(id, cb)
  - getByIds(ids, cb)
  - list(filter, cb)
  - createBasePaths(cb)
  - installDependencies(dapp, cb)
  - getInstalledIds(cb)
  - removeDApp(dapp, cb)
  - downloadLink(dapp, dappPath, cb)
  - installDApp(dapp, cb)
  - createSymlink(dapp, cb)
  - apiHandler(message, callback)
  - createRoutes(dapp, cb)
  - launchDApp(body, cb)
  - createSandbox(dapp, params, cb)
  - stopDApp(dapp, cb)
  -- API --
  .. shared ..
  + getGenesis (dappid, cb)
  + setReady (dappid, cb)
  + getCommonBlock (dappid, cb)
  + sendWithdrawal (req, cb)
  + getWithdrawalLastTransaction (dappid, cb)
  + getBalanceTransactions (lastTransactionId, dappid, cb)
  .. internal ..
  - put (dapp, cb)
  - get (query, cb)
  - list (query, cb)
  - installed (req, cb)
  - search (query, cb)
  - installedIds (req, cb)
  - isMasterPasswordEnabled (req, cb)
  - install (params, cb)
  - uninstall (params, cb)
  - launch (req, cb)
  - installing (req, cb)
  - uninstalling (req, cb)
  - launched (req, cb)
  - categories (req, cb)
  - stop (params, cb)
  - addTransactions (secret, publicKey, secondSecret,
  multisigAccountPublicKey, amount, dappId, cb)
  - sendWithdrawal (secret, multisigAccountPublicKey,
  secondSecret, amount, recipientId, dappId, transactionId, cb)
}
@enduml
