@startuml
class Multisignatures < module > {
  - __private: {}
  - self: this
  .. __private ..
  - assetTypes[4]: new Multisignature (schema,
  network, transaction, logger)
  .. library ..
  - logger
  - db
  - network
  - schema
  - ed
  - bus
  - balancesSequence
  - logic.transaction
  .. modules ..
  - transactions
  - accounts
  -- Methods --
  + Multisignatures (cb, scope)
  + processSignature (tx, cb)
  + sandboxApi (call, args, cb)
  + onBind (scope)
  + isLoaded ()
  -- API --
  .. shared ..
  + getAccounts (publicKey, cb)
  + pending (publicKey, cb)
  + sign (transactionId, secret, publicKey, cb)
  + addMultisignature (secret, publicKey,
  secondSecret, min, keysgroup, lifetime, cb)
}
@enduml
