@startuml
class Sql < module > {
  - __private: {}
  - self: this
  .. library ..
  - logger
  - db
  -- Methods --
  + Sql (cb, scope)
  + createTables (dappid, config, cb)
  + dropTables (dappid, config, cb)
  + sandboxApi (call, args, cb)
  + onBind (scope)
  + onBlockchainReady ()
  .. __private ..
  - escape (what)
  - escape2 (str)
  - pass (obj, dappid)
  - query (action, config, cb)
  .. shared ..
  + select (body, dappid, cb)
  + batch (body, dappid, cb)
  + insert (body, dappid, cb)
  + update (body, dappid, cb)
  + remove (body, dappid, cb)
}
@enduml
