@startuml
class Name < System > {
  - __private: {}
  - self: this
  .. library ..
  - logger
  - db
  - nonce
  - config.version
  - config.port
  - config.nethash
  - config.minVersion
  .. modules ..
  - blocks
  - transport
  -- Methods --
  + System (cb, scope)
  + headers ()
  + getOS ()
  + getVersion ()
  + getPort ()
  + getHeight ()
  + getNethash ()
  + networkCompatible (nethash)
  + getMinVersion ()
  + versionCompatible (version)
  + getBroadhash (cb)
  + update (cb)
  + sandboxApi (call, args, cb)
  + onBind (scope)
}
@enduml
